mysite/abola/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page
app_name = 'abola'

urlpatterns = [
    #path('',cache_page(60*60*24*10)(index), name='index'),#cacge index page for 10 days
    path('',index, name='index'),
    path('<str:team>', cache_page(60*15)(render_team),name='render_team'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('abola/',include('abola.urls')),
    path('npr/',include('npr.urls')),
    
]

mysite/npr/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'npr'

urlpatterns = [
    path('',cache_page(60*60*24*7)(views.IndexView.as_view()),name='index'),#cache 7 days
    path('<str:order>/',views.IndexView.as_view(),name='index_by_order'),
    path('search',views.search,name='search'),
    path('category/<slug:slug>',cache_page(60*60*24*7)(views.CategoryView.as_view()),name= 'by_category'), #cache 7 days
    path('<slug:slug>',cache_page(60*30)(views.PodcastView.as_view()),name='podcast'), #cache 30 mins
    #path('podcast/<int:p_id>/<slug:slug>',views.update_episode,name='update_podcast'),
    path('podcast/<slug:slug>/<int:page>',views.PodcastView.as_view(),name='podcast_by_page'),
]

mysite/abola/models.py
from django.db import models

# Create your models here.

mysite/npr/models.py
from django.db import models
from datetime import date

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(unique=True,blank=True)
    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'

class Podcast(models.Model):
    p_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    link = models.CharField(max_length=1000, blank=True, null=True)
    img = models.CharField(max_length=1000, blank=True, null=True)
    description = models.CharField(max_length=5000, blank=True, null=True)
    slug = models.SlugField(unique=True,blank=True)
    def __str__(self):
        return self.title
    
    #get latest episode date
    def latest_episode(self):
        if self.episode_set.all():
            return self.episode_set.all().order_by('-time')[0].time 
        else:
            return "-"
    def sort_latest_episode(self):
        if self.episode_set.all():
            return self.episode_set.all().order_by('-time')[0].time 
        else:
            return date(1900,1,1)
    
    latest_episode.short_description = 'Latest episode'
    class Meta:

        db_table = 'podcast'

class Episode(models.Model):
    e_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=1000, blank=True, null=True)
    p = models.ForeignKey(Podcast, on_delete=models.CASCADE)
    time = models.DateField(blank=True, null=True)
    teaser = models.CharField(max_length=2000, blank=True, null=True)
    img_link = models.CharField(max_length=2000, blank=True, null=True)
    transcript_link = models.CharField(max_length=2000, blank=True, null=True)
    media_link = models.CharField(max_length=2000, blank=True, null=True)
    slug = models.SlugField(unique=True,blank=True)
    def __str__(self):
        return self.title

    class Meta:
        
        db_table = 'episode'

mysite/abola/views.py
from django.shortcuts import render

from .functions import *

results = None
# Create your views here.
def index(request):
    global results
    results = news_fetch()
    context={
        'results' : results
        }
    print(results)
    return render(request,'base1.html',context)

def render_team(request,team):
    for r in results:
        for k,v in r.items():
            if k == team:
                team_news = resp_render(r[team])
                break
    context={
        'team_news':team_news
    }
    print(team_news)
    return render(request,'base1.html',context)

mysite/npr/views.py
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views import generic
from django.shortcuts import redirect,reverse,render
from django.db.models import Q #多条件查询
from django.http import Http404
from .models import *
from django.utils import timezone
# Create your views here.


class IndexView(generic.ListView):
    template_name='npr/index.html'
    model = Podcast
    
    def get_context_data(self,**kwargs):
        context = super(IndexView,self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()

        order = self.kwargs.get('order') #catch order 
        if order:
            if order=='by_name':
                context['podcast'] = Podcast.objects.all().order_by('title')
            elif order =='by_date':
                context['order'] = 'by_date'
                context['podcast'] = sorted(Podcast.objects.all(),key=lambda podcast: podcast.sort_latest_episode(),reverse=True)
                #order by model custom function (sort_latest_episode)
        else:
            context['podcast'] = Podcast.objects.all()

        context['today'] = timezone.now().date  
        return context

class CategoryView(generic.DetailView):
    template_name='npr/category.html'
    model = Category
    context_object_name = 'selected_category'

    def get_context_data(self,**kwargs):
        context = super(CategoryView,self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context

class PodcastView(generic.DetailView):
    template_name='npr/podcast.html'
    model = Podcast
    context_object_name='podcast'

    def get_context_data(self,**kwargs):
        context = super(PodcastView,self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()#pass in category list

        slug = self.kwargs.get('slug')
        # related podcast exlude showing podcast: get itself instance first, get its category via fk, then get podcasts under 
        #that category via fk, excluding slug field 
        context['related_podcast'] = Podcast.objects.get(slug=slug).category.podcast_set.all().exclude(slug=slug)

        n = self.kwargs.get('page') #catch thrown in page

        episodes = self.object.episode_set.all().order_by('-time')#order episodes by date

        paginator = Paginator(episodes,8)#each page 8 eps

        if n and n >=3:
            context['page_range'] = paginator.page_range[n-3:n+2]
        else:
            context['page_range'] = paginator.page_range[0:5]

        try:
            context['page_n'] = paginator.page(n)
        except PageNotAnInteger:
            context['page_n'] = paginator.page(1) #page 1 by default
        except EmptyPage:
            context['page_n'] = paginator.page(paginator.num_pages) #to last page 

        return context



def search(request):
    try:
        #receive post request: search content
        search_content = request.POST.get('search_content')

        #podcast query with title containing search content
        result_podcast = Podcast.objects.filter(title__icontains=search_content)

        #episodes query with title or teaser containing search content
        result_episode = Episode.objects.filter( Q(title__icontains=search_content)|Q(teaser__icontains=search_content) )


    except ValueError:#catch search content value error
        raise Http404("No result found")

    else:
        context = {
        'category':Category.objects.all(),
        'search_content':search_content,
        'result_podcast':result_podcast,
        'result_episode':result_episode,
        }

    #render results in search.html 
        return render(request,"npr/search.html", context)

mysite/abola/templates/base1.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%block title%}{%endblock%}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="navbar">
        <div class="col-5 col-sm-2 my-2">
            <img src="https://www.abola.pt/img/logoabola.png" alt="Abola logo">
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{%url 'abola:index'%}">News</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.npr.org/music/">Music</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'npr:index'%}">Podcasts</a>
            </li>
          </ul>
        </div>
        <!-- search bar -->
        <form class="col-10 col-sm-6 input-group input-group-sm" action="{% url 'npr:search'%}" method="post" >
          {%csrf_token%}
          <input type="text" class="form-control" name="search_content" placeholder="Search podcast or episode" aria-label="Search" aria-describedby="button-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="submit" id="button-addon2">Search</button>
          </div>
        </form>
    </nav>
    <div class="container">
        {%if results%}
        <div class="row row-cols-2">
          {%for t in results%}
            {%for k,v in t.items%}
            <a href="{%url 'abola:render_team' k%}" class="col list-group-item list-group-item-action">{{k}}</a>
            {%endfor%}
          {%endfor%}
        </div>
        {%endif%}

        {%if team_news%}
        {%for i in team_news%}
        <div class="row align-items-center">
          <div class="col-9">
            <h6>{{i.title}}</h6>
            <p class="small">{{i.time_stamp}}</p>
            <p class="text-body">{{i.body}}</p>
          </div>
          <div class="col-3">
            <img src="{{i.img}}" class="img-fluid" alt="image">
          </div>
          
        </div> 
        {%endfor%}
        {%endif%}
      
          {%block content%}

          {%endblock%}
          <div class="media fixed-top row justify-content-end">
            <div class="media-content mt-0 col-5">
                <h6 id="player-title" class="d-none d-sm-block my-0 pl-3 small">test</h6>
                <audio src="{%static "abola/123.mp3" %}" id="player" class="px-0" preload controls="controls"></audio>
            </div>
        </div>
    </div>

      
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
      {%block script%}
      {%endblock%}
    </body>
</html>

mysite/npr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%block title%}{%endblock%}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="navbar">
        <div class="col-5 col-sm-2 my-2">
            <img src="https://media.npr.org/chrome_svg/npr-logo.svg" alt="NPR logo">
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="https://www.npr.org/sections/news/">News</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.npr.org/music/">Music</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'npr:index'%}">Podcasts</a>
            </li>
          </ul>
        </div>
        <!-- search bar -->
        <form class="col-10 col-sm-6 input-group input-group-sm" action="{% url 'npr:search'%}" method="post" >
          {%csrf_token%}
          <input type="text" class="form-control" name="search_content" placeholder="Search podcast or episode" aria-label="Search" aria-describedby="button-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="submit" id="button-addon2">Search</button>
          </div>
        </form>
    </nav>
    <div class="container">
        <div class="branding px-3 py-1 my-2 border">
          <div class="row align-items-center mb-2">
              <div class="col-2 col-m-1">
                  <img src="https://media.npr.org/branding/podcasts/branding_icon-878de1c87b9393bb958c0e085815af6422ec0162.svg" class="branding__image-icon" alt="Podcast Directory">
              </div>
              <h3 class="col">Featured NPR Podcasts</h2>
          </div>
          <div class="row align-items-center justify-content-between">
              <div class="col-3 dropdown">
                  <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                  </button>
                  <div class="dropdown-menu row" aria-labelledby="dropdownMenuButton">
                    {%for each in category%}
                      <a class="dropdown-item text-muted small" href="{% url 'npr:by_category' each.slug %}">{{each.name}}</a>
                    {%endfor%}
                  </div>
              </div>
              {%block order_btn%}
              {%endblock%}
          </div>
        </div>
          {%block content%}

          {%endblock%}
    </div>

      
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
      {%block script%}
      {%endblock%}
    </body>
</html>

mysite/npr/templates/npr/category.html
{%extends "base.html" %}

{%block title%}NPR: {{selected_category.name}} Podcasts{%endblock%}

{%block content%}

<div class="podcast-list row row-cols-2 row-cols-md-4 row-cols-lg-5">
  {%if selected_category.podcast_set.all%}
    {%for pod in selected_category.podcast_set.all%}
        <div class="card border-0 col">
          <img src="{{pod.img}}" alt="" class="img-thumbnail">
          <div class="card-body px-2 py-1">
            <a href="{%url 'npr:by_category' selected_category.slug%}" class="text-muted small">{{selected_category.name}}</h5></a>
            <a href="{%url 'npr:podcast' pod.slug%}">
              <h6 class="card-title text-body">{{pod.title}}</h6>
            </a>
          </div>
        </div>
    {%endfor%}
  {%else%}
    <h5 class="h4 my-5">No podcast found in this category</h5>
  {%endif%}
</div>

{%endblock%}

mysite/npr/templates/npr/index.html
{%extends "base.html" %}

{%block title%}Podcasts: NPR{%endblock%}

{%block order_btn%}
  <div class="col-auto small px-1">
    <span>Order by: </span>
    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
      <a href="{%url 'npr:index_by_order' 'by_name'%}" type="button" class="btn btn-link">Name</a>
      <a href="{%url 'npr:index_by_order' 'by_date'%}" type="button" class="btn btn-link">Date</a>
    </div>
  </div>
{%endblock%}

{%block content%}

<div class="podcast-list row row-cols-2 row-cols-md-4 row-cols-lg-5">
    {%for pod in podcast%}
      <div class="card border-0 col">
        <img src="{{pod.img}}" alt="{{pod.title}}" class="img-thumbnail">
        <div class="card-body px-2 py-1">
          <h6 class="text-muted small mb-0">{{pod.category}}</h6>
          {%if order == 'by_date'%}
          <h6 class="text-muted small py-1 mb-0">{{pod.latest_episode}}</h6>
          {% endif %}
          <a href="{%url 'npr:podcast' pod.slug %}">
            <h6 class="card-title text-body">{{pod.title}}</h6>
          </a>
          
        </div>
      </div>
    {%endfor%}
  
</div>

{%endblock%}

mysite/npr/templates/npr/podcast.html
{%extends 'base.html'%}

{%block title%}
    {{podcast.title}}
{%endblock%}


{%block content%}
    
    <div class="podcast-overview border p-3 mb-3">
        <div class="row align-items-center">
            <div class="col-12 d-sm-none d-md-block col-md-3">
                <img src="{{podcast.img}}" alt="{{podcast.title}}" class="img-thumbnail border-0 p-2">
            </div>
            <div class="col">
                <ul class="breadcrumb bg-light py-1 px-0 mb-0">
                    <li><a href="{%url 'npr:index'%}" class="text-body">Podcast</a><span> >&nbsp;</span></li>
                    <li><a href="{%url 'npr:by_category' podcast.category.slug%}" class="text-info">{{podcast.category}}</a></li>
                </ul>
                <h3>{{podcast.title}}</h3>
                <p class="podcast-description text-secondary">{{podcast.description}}</p>
                <p class="latest">Latest episode: {{podcast.latest_episode}}</p>
            </div>
        </div>
    </div>

    <div class="main-section my-2 px-2">
        <div class="row justify-content-around">
            <!-- related pod/redirection  -->
            <div class="related d-none d-md-block col-md-4">
                <div class="related-podcast">
                    {%if related_podcast%}
                    <h5 class="text-warning">RELATED PODCASTS</h5>
                        {%for p in related_podcast%}
                        <div class="row align-items-center">
                            <div class="col-4">
                                <img src="{{p.img}}" alt="" class="img-thumbnail">
                            </div>
                            <div class="col-8 pl-0">
                                <a href="{%url 'npr:podcast' p.slug%}"><h6 class="text-body">{{p.title}}</h6></a>
                            </div>
                        </div>
                        {%endfor%}
                    {%endif%}
                </div>
                <div class="redirection list-group list-group-flush mt-2">
                    <li class="list-group-item"><a href="{%url 'npr:index'%}">View All Podcasts from NPR</a></li>
                    <li class="list-group-item"><a href="{%url 'npr:by_category' podcast.category.slug%}">View All Podcasts from {{podcast.category}}</a></li>
                </div>

            </div>
           
            <div class="episodes col-md-8">
                <h5 class="text-info">Most Recent Episodes</h5>

                {%for ep in page_n%}
                 <!-- episode info -->
                    <div class="episode border-bottom border-secondary pt-2">
                        <div class="episode-info">
                            <div class="row align-items-center">
                                {%if ep.img_link%}
                                <div class="col">
                                    <h6 class="small">{{ep.time}}</h6>
                                    <a href="{%url 'npr:podcast' ep.slug%}"><h6 class="text-body">{{ep.title}}</h6></a>
                                    <div class="text-secondary">{{ep.teaser}}</div>
                                </div>
                                <div class="d-none d-sm-block col-4">
                                    <img src="{{ep.img_link}}" alt="" class="img-fluid">
                                </div>
                                {%else%}
                                <div class="col">
                                    <h6 class="small">{{ep.time}}</h6>
                                    <h6>{{ep.title}}</h6>
                                    <div class="small">{{ep.teaser}}</div>
                                </div>
                                {%endif%}
                                
                            </div>
                        </div>
                        <!-- episode control: play/download/transcript -->
                        <div class="episode-control my-2">
                            <div class="row justify-content-start">
                                <div class="btn-group col-auto" role="group" aria-label="Basic example">
                                    {%if ep.media_link%}
                                    <a class="play-button btn btn-outline-primary text-primary px-3 btn-sm mr-1" title="{{ep.title}}" value="{{ep.media_link}}">Play </a>
                                    {%endif%}
                                    {%if ep.media_link%}
                                    <a href="{{ep.media_link}}" class="btn btn-outline-info text-success btn-sm mr-1">Download</a>
                                    {%endif%}
                                    {%if ep.transcript_link%}
                                    <a href="{{ep.transcript_link}}" target="_blank" class="btn btn-outline-warning text-warning btn-sm mr-1">Transcrpit</a>
                                    {%endif%}
                                </div>
                            </div>
                        </div>
                    </div>
                {%endfor%}
            </div>
        </div>   
    </div>

    <!-- pagination -->
    <nav aria-label="Page">
        <ul class="pagination pagination-sm row justify-content-center mt-3">
        <!-- to 1st page -->
            <li class="page-item">
                <a class="page-link" href="{%url 'npr:podcast_by_page' podcast.slug page_n.paginator.page_range.0 %}" aria-label="Next">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {%if page_n.has_previous%}
        <!-- to previous page -->
            <li class="page-item">
              <a class="page-link" href="{%url 'npr:podcast_by_page' podcast.slug page_n.previous_page_number%}" aria-label="Next">
                <span aria-hidden="true">&lt;</span>
              </a>
            </li>
            {%endif%}
        <!-- render page number & link -->
          {%for pg in page_range%}
            <li class="page-item {%if page_n.number == pg %}active{%endif%}"><a class="page-link" href="{%url 'npr:podcast_by_page' podcast.slug pg%}">{{pg}}</a></li>
          {%endfor%}
          <!-- to next page -->
          {%if page_n.has_next%}
          <li class="page-item">
            <a class="page-link" href="{%url 'npr:podcast_by_page' podcast.slug page_n.next_page_number%}" aria-label="Next">
              <span aria-hidden="true">&gt;</span>
            </a>
          </li>
          {%endif%}
          <!-- to last page -->
          <li class="page-item">
            <a class="page-link" href="{%url 'npr:podcast_by_page' podcast.slug page_n.paginator.num_pages%}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>

      <!-- html5 player -->
    <div class="media fixed-top row justify-content-end">
        <div class="media-content mt-0 col-5">
            <h6 id="player-title" class="d-none d-sm-block my-0 pl-3 small">{{podcast.title}}</h6>
            <audio src="" id="player" class="px-0" preload controls="controls"></audio>
        </div>
    </div>

{%endblock%}

<!-- player control play episode -->
{%block script%}
<script>
$( ".play-button" ).click(function() {
    var src = $(this).attr('value')
    var title = $(this).attr('title')
    $('#player-title').text(title)
    $('#player').attr('src',src)
    $('#player')[0].play();
});
</script>
{%endblock%}

mysite/npr/templates/npr/search.html
{%extends "base.html" %}
{% load npr_extras %}


{%block title%}Search result: {{search_content}}{%endblock%}

{%block content%}
<div class="podcast-list">
    <div class="row">
        <h5 class="col">Search results: <span class="text-primary">{{search_content}}</span></h5>
    </div>
    <!-- render podcast search in exist -->
    {%if result_podcast%}
    <div class="row">
        <h5 class="col text-warning my-2">Podcast</h5>
    </div>
    <div class="row justify-content-start"> -->
    {%for pod in result_podcast%}
      <div class="card border-0 col col-md-3 my-2">
        <img src="{{pod.img}}" alt="" class="img-thumbnail">
        <div class="card-body px-2 py-1">
          <h6 class="text-muted small">{{pod.category}}</h6>
          <a href="{%url 'npr:update_podcast' pod.p_id pod.slug %}">
            <h6 class="card-title text-body">{{pod.title|highlight:search_content}}</h6>
          </a>
       
          </p>
        </div>
      </div>
    {%endfor%}
    </div>
    {%endif%}

    <!-- render episode search if exist -->
    {%if result_episode%}
    <div class="row">
        <h5 class="col text-warning my-2">Episodes</h5>
    </div>
    {%for ep in result_episode%}
    <!-- episode info -->
       <div class="episode border-bottom border-light py-3">
           <div class="episode-info">
               <div class="row align-items-center">
                   {%if ep.img_link%}
                   <div class="col">
                       <h6 class="small text-secondary"> {{ep.p}}</h6>
                        <!-- highlight search content by custom template filter -->
                       <a href="{%url 'npr:podcast' ep.slug%}"><h6 class="text-body">{{ep.title|highlight:search_content}}</h6></a>
                       <div class="text-secondary">{{ep.teaser|highlight:search_content}}</div>
                   </div>
                   <div class="d-none d-md-block col-3">
                       <img src="{{ep.img_link}}" alt="" class="img-fluid">
                   </div>
                   {%else%}
                   <div class="col pr-2">
                        <h6 class="small text-secondary"> {{ep.p}}</h6>
                       <h6 class="text-body">{{ep.title|highlight:search_content}}</h6>
                       <div class="text-secondary">{{ep.teaser|highlight:search_content}}</div>
                   </div>
                   {%endif%}
                   
               </div>
           </div>
           <div class="episode-control my-2">
            <div class="row justify-content-start">
                <div class="btn-group col-auto" role="group" aria-label="Basic example">
                    {%if ep.media_link%}
                    <a class="play-button btn btn-outline-primary text-primary px-3 btn-sm mr-1" title="{{ep.title}}" value="{{ep.media_link}}">Play </a>
                    {%endif%}
                    {%if ep.media_link%}
                    <a href="{{ep.media_link}}" class="btn btn-outline-info text-success btn-sm mr-1">Download</a>
                    {%endif%}
                    {%if ep.transcript_link%}
                    <a href="{{ep.transcript_link}}" target="_blank" class="btn btn-outline-warning text-warning btn-sm mr-1">Transcrpit</a>
                    {%endif%}
                </div>
            </div>
        </div>
        </div>
    {%endfor%}
    {%endif%}
    <div class="media fixed-top row justify-content-end">
        <div class="media-content mt-0 col-5">
            <h6 id="player-title" class="d-none d-sm-block my-0 pl-3 small">{{podcast.title}}</h6>
            <audio src="" id="player" class="px-0" preload controls="controls"></audio>
        </div>
    </div>
</div>
{%endblock%}

{%block script%}
<script>
$( ".play-button" ).click(function() {
    var src = $(this).attr('value')
    var title = $(this).attr('title')
    $('#player-title').text(title)
    $('#player').attr('src',src)
    $('#player')[0].play();
});
</script>
{%endblock%}